/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'id' : string,
  'userId' : UserId,
  'description' : string,
  'timestamp' : Timestamp,
  'relatedId' : [] | [string],
  'eventType' : string,
}
export type AssetId = string;
export interface AuditFilters {
  'page' : bigint,
  'pageSize' : bigint,
  'actionType' : [] | [string],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'adminId' : [] | [UserId],
}
export interface AuditLog {
  'id' : string,
  'status' : string,
  'action' : string,
  'adminName' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'affectedId' : [] | [string],
  'adminId' : UserId,
}
export interface ChatMessage { 'content' : string, 'role' : string }
export interface Conversation {
  'id' : ConversationId,
  'status' : ConversationStatus,
  'lastMessageAt' : Timestamp,
  'createdAt' : Timestamp,
  'productId' : string,
  'buyerId' : UserId,
  'sellerId' : UserId,
}
export type ConversationId = string;
export type ConversationStatus = { 'active' : null } |
  { 'archived' : null };
export interface DashboardStats {
  'totalProducts' : bigint,
  'newUsersToday' : bigint,
  'pendingReports' : bigint,
  'activeListings' : bigint,
  'totalReports' : bigint,
  'blockedProducts' : bigint,
  'totalUsers' : bigint,
  'newProductsToday' : bigint,
}
export interface Message {
  'id' : MessageId,
  'authorId' : UserId,
  'text' : string,
  'readBySeller' : boolean,
  'conversationId' : ConversationId,
  'timestamp' : Timestamp,
  'readByBuyer' : boolean,
}
export type MessageId = string;
export interface Notification {
  'id' : string,
  'title' : string,
  'body' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'relatedId' : [] | [string],
}
export type NotificationType = { 'newProduct' : null } |
  { 'newMessage' : null } |
  { 'productUpdate' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'productId' : string,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'stripePaymentIntentId' : string,
  'amountMxn' : bigint,
  'sellerId' : UserId,
}
export type OrderId = string;
export interface OrderStats {
  'totalOrders' : bigint,
  'ordersThisMonth' : bigint,
  'ordersThisWeek' : bigint,
  'ordersToday' : bigint,
  'totalRevenue' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface Product {
  'id' : string,
  'status' : ProductStatus,
  'title' : string,
  'isApartado' : boolean,
  'featured' : boolean,
  'views' : bigint,
  'createdAt' : Timestamp,
  'zone' : ProductZone,
  'description' : string,
  'whatsappContact' : [] | [string],
  'category' : ProductCategory,
  'sellerId' : UserId,
  'colony' : string,
  'price' : number,
  'photos' : Array<AssetId>,
  'negotiable' : boolean,
  'condition' : ProductCondition,
}
export type ProductCategory = { 'mueble' : null } |
  { 'auto' : null } |
  { 'otro' : null } |
  { 'ropa' : null } |
  { 'electronico' : null };
export type ProductCondition = { 'nuevo' : null } |
  { 'usado' : null };
export interface ProductFilters {
  'status' : [] | [ProductStatus],
  'zone' : [] | [ProductZone],
  'searchTerm' : [] | [string],
  'category' : [] | [ProductCategory],
  'priceMax' : [] | [number],
  'priceMin' : [] | [number],
  'condition' : [] | [ProductCondition],
}
export type ProductStatus = { 'active' : null } |
  { 'blocked' : null } |
  { 'hidden' : null } |
  { 'paused' : null };
export type ProductZone = { 'centro' : null } |
  { 'playas' : null } |
  { 'otay' : null } |
  { 'corredor2000' : null };
export interface Rating {
  'id' : string,
  'toSellerId' : UserId,
  'createdAt' : Timestamp,
  'productId' : string,
  'score' : bigint,
  'comment' : string,
  'fromUserId' : UserId,
}
export interface Report {
  'id' : string,
  'status' : ReportStatus,
  'createdAt' : Timestamp,
  'description' : string,
  'adminNote' : [] | [string],
  'reportType' : ReportType,
  'reporterId' : UserId,
  'entityId' : string,
  'reason' : string,
}
export type ReportStatus = { 'new' : null } |
  { 'resolved' : null } |
  { 'inReview' : null };
export type ReportType = { 'chat' : null } |
  { 'user' : null } |
  { 'product' : null };
export interface RevenueByDay { 'revenue' : bigint, 'date' : string }
export interface SavedProduct {
  'userId' : UserId,
  'productId' : string,
  'savedAt' : Timestamp,
}
export interface SellerStats {
  'totalOrders' : bigint,
  'revenueByDay' : Array<RevenueByDay>,
  'conversionRate' : number,
  'topProducts' : Array<TopProduct>,
  'totalRevenue' : bigint,
  'avgOrderValue' : bigint,
}
export interface SiteConfig {
  'metaDescription' : string,
  'analyticsId' : string,
  'maintenanceMode' : boolean,
  'siteName' : string,
  'logoUrl' : string,
  'siteDescription' : string,
  'contactEmail' : string,
}
export type Timestamp = bigint;
export interface TopProduct {
  'title' : string,
  'revenue' : bigint,
  'views' : bigint,
  'orders' : bigint,
  'productId' : string,
}
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'bio' : [] | [string],
  'status' : UserStatus,
  'timezone' : string,
  'principal' : Principal,
  'verified' : boolean,
  'privacySearchable' : boolean,
  'dateOfBirth' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'zone' : [] | [string],
  'themePreference' : string,
  'email' : [] | [string],
  'language' : string,
  'totalSales' : bigint,
  'avatarUrl' : [] | [string],
  'currency' : string,
  'privacyShowHistory' : boolean,
  'frequentClients' : Array<UserId>,
  'phone' : string,
  'notificationsEmail' : boolean,
  'notificationsPush' : boolean,
  'avgRating' : number,
}
export type UserRole = { 'admin' : null } |
  { 'vendedor' : null } |
  { 'comprador' : null };
export interface UserSettings {
  'timezone' : string,
  'privacySearchable' : boolean,
  'themePreference' : string,
  'language' : string,
  'currency' : string,
  'privacyShowHistory' : boolean,
  'notificationsEmail' : boolean,
  'notificationsPush' : boolean,
}
export type UserStatus = { 'active' : null } |
  { 'banned' : null } |
  { 'suspended' : null };
export interface _SERVICE {
  'addAdminNote' : ActorMethod<[string, string], Report>,
  'addFrequentClient' : ActorMethod<[UserId], UserProfile>,
  'addRating' : ActorMethod<[UserId, string, bigint, string], Rating>,
  'chatWithAviBot' : ActorMethod<[string, Array<ChatMessage>], string>,
  'createCheckoutSession' : ActorMethod<
    [string, string, string],
    { 'checkoutUrl' : string }
  >,
  'createConversation' : ActorMethod<[UserId, string], Conversation>,
  'createOrder' : ActorMethod<[string, UserId, bigint, string], Order>,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      number,
      boolean,
      ProductCategory,
      ProductCondition,
      ProductZone,
      string,
      Array<string>,
      [] | [string],
      boolean,
    ],
    Product
  >,
  'createReport' : ActorMethod<[ReportType, string, string, string], Report>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[UserId], undefined>,
  'featureProduct' : ActorMethod<[string, boolean], Product>,
  'getActivityByUser' : ActorMethod<[UserId], Array<ActivityEvent>>,
  'getConfig' : ActorMethod<[], SiteConfig>,
  'getConversationMessages' : ActorMethod<[ConversationId], Array<Message>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyActivity' : ActorMethod<[], Array<ActivityEvent>>,
  'getMyConversations' : ActorMethod<[], Array<Conversation>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyRatings' : ActorMethod<[], Array<Rating>>,
  'getMySavedProducts' : ActorMethod<[], Array<SavedProduct>>,
  'getMySellerOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductPhotoIds' : ActorMethod<[string], Array<string>>,
  'getProductViewCount' : ActorMethod<[string], bigint>,
  'getProductsByVendor' : ActorMethod<[UserId], Array<Product>>,
  'getRatingsBySeller' : ActorMethod<[UserId], Array<Rating>>,
  'getSellerOrderStats' : ActorMethod<[], OrderStats>,
  'getSellerStats' : ActorMethod<[], SellerStats>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserById' : ActorMethod<[UserId], [] | [UserProfile]>,
  'incrementProductViews' : ActorMethod<[string], undefined>,
  'isMaintenanceMode' : ActorMethod<[], boolean>,
  'listAuditLogs' : ActorMethod<[AuditFilters], Array<AuditLog>>,
  'listMyActivity' : ActorMethod<[], Array<ActivityEvent>>,
  'listProducts' : ActorMethod<[ProductFilters], Array<Product>>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markConversationAsRead' : ActorMethod<[ConversationId], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      UserRole,
    ],
    UserProfile
  >,
  'removeFrequentClient' : ActorMethod<[UserId], UserProfile>,
  'saveProduct' : ActorMethod<[string], SavedProduct>,
  'seedSampleData' : ActorMethod<[], bigint>,
  'sendMessage' : ActorMethod<[ConversationId, string], Message>,
  'trackProductView' : ActorMethod<[string], undefined>,
  'unsaveProduct' : ActorMethod<[string], undefined>,
  'updateConfig' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [string],
      [] | [string],
    ],
    SiteConfig
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], Order>,
  'updateProduct' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [boolean],
      [] | [ProductCategory],
      [] | [ProductCondition],
      [] | [ProductZone],
      [] | [string],
      [] | [Array<string>],
      [] | [string],
      [] | [boolean],
    ],
    Product
  >,
  'updateProductStatus' : ActorMethod<[string, ProductStatus], Product>,
  'updateProfile' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [boolean],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [boolean],
    ],
    UserProfile
  >,
  'updateReportStatus' : ActorMethod<[string, ReportStatus], Report>,
  'updateSettings' : ActorMethod<[UserSettings], UserProfile>,
  'updateUserStatus' : ActorMethod<[UserId, UserStatus], UserProfile>,
  'verifyUser' : ActorMethod<[UserId], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];