/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReportStatus = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'inReview' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ReportType = IDL.Variant({
  'chat' : IDL.Null,
  'user' : IDL.Null,
  'product' : IDL.Null,
});
export const UserId = IDL.Text;
export const Report = IDL.Record({
  'id' : IDL.Text,
  'status' : ReportStatus,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'adminNote' : IDL.Opt(IDL.Text),
  'reportType' : ReportType,
  'reporterId' : UserId,
  'entityId' : IDL.Text,
  'reason' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'banned' : IDL.Null,
  'suspended' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'vendedor' : IDL.Null,
  'comprador' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'status' : UserStatus,
  'timezone' : IDL.Text,
  'principal' : IDL.Principal,
  'verified' : IDL.Bool,
  'privacySearchable' : IDL.Bool,
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'zone' : IDL.Opt(IDL.Text),
  'themePreference' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'language' : IDL.Text,
  'totalSales' : IDL.Nat,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'privacyShowHistory' : IDL.Bool,
  'frequentClients' : IDL.Vec(UserId),
  'phone' : IDL.Text,
  'notificationsEmail' : IDL.Bool,
  'notificationsPush' : IDL.Bool,
  'avgRating' : IDL.Float64,
});
export const Rating = IDL.Record({
  'id' : IDL.Text,
  'toSellerId' : UserId,
  'createdAt' : Timestamp,
  'productId' : IDL.Text,
  'score' : IDL.Nat,
  'comment' : IDL.Text,
  'fromUserId' : UserId,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const ConversationId = IDL.Text;
export const ConversationStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'status' : ConversationStatus,
  'lastMessageAt' : Timestamp,
  'createdAt' : Timestamp,
  'productId' : IDL.Text,
  'buyerId' : UserId,
  'sellerId' : UserId,
});
export const OrderId = IDL.Text;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'productId' : IDL.Text,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'stripePaymentIntentId' : IDL.Text,
  'amountMxn' : IDL.Nat,
  'sellerId' : UserId,
});
export const ProductCategory = IDL.Variant({
  'mueble' : IDL.Null,
  'auto' : IDL.Null,
  'otro' : IDL.Null,
  'ropa' : IDL.Null,
  'electronico' : IDL.Null,
});
export const ProductCondition = IDL.Variant({
  'nuevo' : IDL.Null,
  'usado' : IDL.Null,
});
export const ProductZone = IDL.Variant({
  'centro' : IDL.Null,
  'playas' : IDL.Null,
  'otay' : IDL.Null,
  'corredor2000' : IDL.Null,
});
export const ProductStatus = IDL.Variant({
  'active' : IDL.Null,
  'blocked' : IDL.Null,
  'hidden' : IDL.Null,
  'paused' : IDL.Null,
});
export const AssetId = IDL.Text;
export const Product = IDL.Record({
  'id' : IDL.Text,
  'status' : ProductStatus,
  'title' : IDL.Text,
  'isApartado' : IDL.Bool,
  'featured' : IDL.Bool,
  'views' : IDL.Nat,
  'createdAt' : Timestamp,
  'zone' : ProductZone,
  'description' : IDL.Text,
  'whatsappContact' : IDL.Opt(IDL.Text),
  'category' : ProductCategory,
  'sellerId' : UserId,
  'colony' : IDL.Text,
  'price' : IDL.Float64,
  'photos' : IDL.Vec(AssetId),
  'negotiable' : IDL.Bool,
  'condition' : ProductCondition,
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Text,
  'userId' : UserId,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'relatedId' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Text,
});
export const SiteConfig = IDL.Record({
  'metaDescription' : IDL.Text,
  'analyticsId' : IDL.Text,
  'maintenanceMode' : IDL.Bool,
  'siteName' : IDL.Text,
  'logoUrl' : IDL.Text,
  'siteDescription' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'authorId' : UserId,
  'text' : IDL.Text,
  'readBySeller' : IDL.Bool,
  'conversationId' : ConversationId,
  'timestamp' : Timestamp,
  'readByBuyer' : IDL.Bool,
});
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'newUsersToday' : IDL.Nat,
  'pendingReports' : IDL.Nat,
  'activeListings' : IDL.Nat,
  'totalReports' : IDL.Nat,
  'blockedProducts' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'newProductsToday' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'newProduct' : IDL.Null,
  'newMessage' : IDL.Null,
  'productUpdate' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'relatedId' : IDL.Opt(IDL.Text),
});
export const SavedProduct = IDL.Record({
  'userId' : UserId,
  'productId' : IDL.Text,
  'savedAt' : Timestamp,
});
export const OrderStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'ordersThisMonth' : IDL.Nat,
  'ordersThisWeek' : IDL.Nat,
  'ordersToday' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const RevenueByDay = IDL.Record({
  'revenue' : IDL.Nat,
  'date' : IDL.Text,
});
export const TopProduct = IDL.Record({
  'title' : IDL.Text,
  'revenue' : IDL.Nat,
  'views' : IDL.Nat,
  'orders' : IDL.Nat,
  'productId' : IDL.Text,
});
export const SellerStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'revenueByDay' : IDL.Vec(RevenueByDay),
  'conversionRate' : IDL.Float64,
  'topProducts' : IDL.Vec(TopProduct),
  'totalRevenue' : IDL.Nat,
  'avgOrderValue' : IDL.Nat,
});
export const AuditFilters = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'actionType' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'adminId' : IDL.Opt(UserId),
});
export const AuditLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'action' : IDL.Text,
  'adminName' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'affectedId' : IDL.Opt(IDL.Text),
  'adminId' : UserId,
});
export const ProductFilters = IDL.Record({
  'status' : IDL.Opt(ProductStatus),
  'zone' : IDL.Opt(ProductZone),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ProductCategory),
  'priceMax' : IDL.Opt(IDL.Float64),
  'priceMin' : IDL.Opt(IDL.Float64),
  'condition' : IDL.Opt(ProductCondition),
});
export const UserSettings = IDL.Record({
  'timezone' : IDL.Text,
  'privacySearchable' : IDL.Bool,
  'themePreference' : IDL.Text,
  'language' : IDL.Text,
  'currency' : IDL.Text,
  'privacyShowHistory' : IDL.Bool,
  'notificationsEmail' : IDL.Bool,
  'notificationsPush' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addAdminNote' : IDL.Func([IDL.Text, IDL.Text], [Report], []),
  'addFrequentClient' : IDL.Func([UserId], [UserProfile], []),
  'addRating' : IDL.Func([UserId, IDL.Text, IDL.Nat, IDL.Text], [Rating], []),
  'chatWithAviBot' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'checkoutUrl' : IDL.Text })],
      [],
    ),
  'createConversation' : IDL.Func([UserId, IDL.Text], [Conversation], []),
  'createOrder' : IDL.Func([IDL.Text, UserId, IDL.Nat, IDL.Text], [Order], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Bool,
        ProductCategory,
        ProductCondition,
        ProductZone,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [Product],
      [],
    ),
  'createReport' : IDL.Func(
      [ReportType, IDL.Text, IDL.Text, IDL.Text],
      [Report],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([UserId], [], []),
  'featureProduct' : IDL.Func([IDL.Text, IDL.Bool], [Product], []),
  'getActivityByUser' : IDL.Func([UserId], [IDL.Vec(ActivityEvent)], ['query']),
  'getConfig' : IDL.Func([], [SiteConfig], ['query']),
  'getConversationMessages' : IDL.Func(
      [ConversationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getMyConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
  'getMySavedProducts' : IDL.Func([], [IDL.Vec(SavedProduct)], ['query']),
  'getMySellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductPhotoIds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getProductViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getProductsByVendor' : IDL.Func([UserId], [IDL.Vec(Product)], ['query']),
  'getRatingsBySeller' : IDL.Func([UserId], [IDL.Vec(Rating)], ['query']),
  'getSellerOrderStats' : IDL.Func([], [OrderStats], ['query']),
  'getSellerStats' : IDL.Func([], [SellerStats], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'incrementProductViews' : IDL.Func([IDL.Text], [], []),
  'isMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
  'listAuditLogs' : IDL.Func([AuditFilters], [IDL.Vec(AuditLog)], ['query']),
  'listMyActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'listProducts' : IDL.Func([ProductFilters], [IDL.Vec(Product)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markConversationAsRead' : IDL.Func([ConversationId], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        UserRole,
      ],
      [UserProfile],
      [],
    ),
  'removeFrequentClient' : IDL.Func([UserId], [UserProfile], []),
  'saveProduct' : IDL.Func([IDL.Text], [SavedProduct], []),
  'seedSampleData' : IDL.Func([], [IDL.Nat], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
  'trackProductView' : IDL.Func([IDL.Text], [], []),
  'unsaveProduct' : IDL.Func([IDL.Text], [], []),
  'updateConfig' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [SiteConfig],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [Order], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Bool),
        IDL.Opt(ProductCategory),
        IDL.Opt(ProductCondition),
        IDL.Opt(ProductZone),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [Product],
      [],
    ),
  'updateProductStatus' : IDL.Func([IDL.Text, ProductStatus], [Product], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
      ],
      [UserProfile],
      [],
    ),
  'updateReportStatus' : IDL.Func([IDL.Text, ReportStatus], [Report], []),
  'updateSettings' : IDL.Func([UserSettings], [UserProfile], []),
  'updateUserStatus' : IDL.Func([UserId, UserStatus], [UserProfile], []),
  'verifyUser' : IDL.Func([UserId], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReportStatus = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'inReview' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ReportType = IDL.Variant({
    'chat' : IDL.Null,
    'user' : IDL.Null,
    'product' : IDL.Null,
  });
  const UserId = IDL.Text;
  const Report = IDL.Record({
    'id' : IDL.Text,
    'status' : ReportStatus,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'adminNote' : IDL.Opt(IDL.Text),
    'reportType' : ReportType,
    'reporterId' : UserId,
    'entityId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'vendedor' : IDL.Null,
    'comprador' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'status' : UserStatus,
    'timezone' : IDL.Text,
    'principal' : IDL.Principal,
    'verified' : IDL.Bool,
    'privacySearchable' : IDL.Bool,
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'zone' : IDL.Opt(IDL.Text),
    'themePreference' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'language' : IDL.Text,
    'totalSales' : IDL.Nat,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'privacyShowHistory' : IDL.Bool,
    'frequentClients' : IDL.Vec(UserId),
    'phone' : IDL.Text,
    'notificationsEmail' : IDL.Bool,
    'notificationsPush' : IDL.Bool,
    'avgRating' : IDL.Float64,
  });
  const Rating = IDL.Record({
    'id' : IDL.Text,
    'toSellerId' : UserId,
    'createdAt' : Timestamp,
    'productId' : IDL.Text,
    'score' : IDL.Nat,
    'comment' : IDL.Text,
    'fromUserId' : UserId,
  });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const ConversationId = IDL.Text;
  const ConversationStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'status' : ConversationStatus,
    'lastMessageAt' : Timestamp,
    'createdAt' : Timestamp,
    'productId' : IDL.Text,
    'buyerId' : UserId,
    'sellerId' : UserId,
  });
  const OrderId = IDL.Text;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'productId' : IDL.Text,
    'updatedAt' : Timestamp,
    'buyerId' : UserId,
    'stripePaymentIntentId' : IDL.Text,
    'amountMxn' : IDL.Nat,
    'sellerId' : UserId,
  });
  const ProductCategory = IDL.Variant({
    'mueble' : IDL.Null,
    'auto' : IDL.Null,
    'otro' : IDL.Null,
    'ropa' : IDL.Null,
    'electronico' : IDL.Null,
  });
  const ProductCondition = IDL.Variant({
    'nuevo' : IDL.Null,
    'usado' : IDL.Null,
  });
  const ProductZone = IDL.Variant({
    'centro' : IDL.Null,
    'playas' : IDL.Null,
    'otay' : IDL.Null,
    'corredor2000' : IDL.Null,
  });
  const ProductStatus = IDL.Variant({
    'active' : IDL.Null,
    'blocked' : IDL.Null,
    'hidden' : IDL.Null,
    'paused' : IDL.Null,
  });
  const AssetId = IDL.Text;
  const Product = IDL.Record({
    'id' : IDL.Text,
    'status' : ProductStatus,
    'title' : IDL.Text,
    'isApartado' : IDL.Bool,
    'featured' : IDL.Bool,
    'views' : IDL.Nat,
    'createdAt' : Timestamp,
    'zone' : ProductZone,
    'description' : IDL.Text,
    'whatsappContact' : IDL.Opt(IDL.Text),
    'category' : ProductCategory,
    'sellerId' : UserId,
    'colony' : IDL.Text,
    'price' : IDL.Float64,
    'photos' : IDL.Vec(AssetId),
    'negotiable' : IDL.Bool,
    'condition' : ProductCondition,
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Text,
    'userId' : UserId,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'relatedId' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Text,
  });
  const SiteConfig = IDL.Record({
    'metaDescription' : IDL.Text,
    'analyticsId' : IDL.Text,
    'maintenanceMode' : IDL.Bool,
    'siteName' : IDL.Text,
    'logoUrl' : IDL.Text,
    'siteDescription' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'authorId' : UserId,
    'text' : IDL.Text,
    'readBySeller' : IDL.Bool,
    'conversationId' : ConversationId,
    'timestamp' : Timestamp,
    'readByBuyer' : IDL.Bool,
  });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'newUsersToday' : IDL.Nat,
    'pendingReports' : IDL.Nat,
    'activeListings' : IDL.Nat,
    'totalReports' : IDL.Nat,
    'blockedProducts' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'newProductsToday' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'newProduct' : IDL.Null,
    'newMessage' : IDL.Null,
    'productUpdate' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  const SavedProduct = IDL.Record({
    'userId' : UserId,
    'productId' : IDL.Text,
    'savedAt' : Timestamp,
  });
  const OrderStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'ordersThisMonth' : IDL.Nat,
    'ordersThisWeek' : IDL.Nat,
    'ordersToday' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const RevenueByDay = IDL.Record({ 'revenue' : IDL.Nat, 'date' : IDL.Text });
  const TopProduct = IDL.Record({
    'title' : IDL.Text,
    'revenue' : IDL.Nat,
    'views' : IDL.Nat,
    'orders' : IDL.Nat,
    'productId' : IDL.Text,
  });
  const SellerStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'revenueByDay' : IDL.Vec(RevenueByDay),
    'conversionRate' : IDL.Float64,
    'topProducts' : IDL.Vec(TopProduct),
    'totalRevenue' : IDL.Nat,
    'avgOrderValue' : IDL.Nat,
  });
  const AuditFilters = IDL.Record({
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'actionType' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'adminId' : IDL.Opt(UserId),
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'action' : IDL.Text,
    'adminName' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'affectedId' : IDL.Opt(IDL.Text),
    'adminId' : UserId,
  });
  const ProductFilters = IDL.Record({
    'status' : IDL.Opt(ProductStatus),
    'zone' : IDL.Opt(ProductZone),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ProductCategory),
    'priceMax' : IDL.Opt(IDL.Float64),
    'priceMin' : IDL.Opt(IDL.Float64),
    'condition' : IDL.Opt(ProductCondition),
  });
  const UserSettings = IDL.Record({
    'timezone' : IDL.Text,
    'privacySearchable' : IDL.Bool,
    'themePreference' : IDL.Text,
    'language' : IDL.Text,
    'currency' : IDL.Text,
    'privacyShowHistory' : IDL.Bool,
    'notificationsEmail' : IDL.Bool,
    'notificationsPush' : IDL.Bool,
  });
  
  return IDL.Service({
    'addAdminNote' : IDL.Func([IDL.Text, IDL.Text], [Report], []),
    'addFrequentClient' : IDL.Func([UserId], [UserProfile], []),
    'addRating' : IDL.Func([UserId, IDL.Text, IDL.Nat, IDL.Text], [Rating], []),
    'chatWithAviBot' : IDL.Func(
        [IDL.Text, IDL.Vec(ChatMessage)],
        [IDL.Text],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'checkoutUrl' : IDL.Text })],
        [],
      ),
    'createConversation' : IDL.Func([UserId, IDL.Text], [Conversation], []),
    'createOrder' : IDL.Func(
        [IDL.Text, UserId, IDL.Nat, IDL.Text],
        [Order],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Bool,
          ProductCategory,
          ProductCondition,
          ProductZone,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [Product],
        [],
      ),
    'createReport' : IDL.Func(
        [ReportType, IDL.Text, IDL.Text, IDL.Text],
        [Report],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([UserId], [], []),
    'featureProduct' : IDL.Func([IDL.Text, IDL.Bool], [Product], []),
    'getActivityByUser' : IDL.Func(
        [UserId],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getConfig' : IDL.Func([], [SiteConfig], ['query']),
    'getConversationMessages' : IDL.Func(
        [ConversationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getMyConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
    'getMySavedProducts' : IDL.Func([], [IDL.Vec(SavedProduct)], ['query']),
    'getMySellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductPhotoIds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getProductViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getProductsByVendor' : IDL.Func([UserId], [IDL.Vec(Product)], ['query']),
    'getRatingsBySeller' : IDL.Func([UserId], [IDL.Vec(Rating)], ['query']),
    'getSellerOrderStats' : IDL.Func([], [OrderStats], ['query']),
    'getSellerStats' : IDL.Func([], [SellerStats], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'incrementProductViews' : IDL.Func([IDL.Text], [], []),
    'isMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
    'listAuditLogs' : IDL.Func([AuditFilters], [IDL.Vec(AuditLog)], ['query']),
    'listMyActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'listProducts' : IDL.Func([ProductFilters], [IDL.Vec(Product)], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markConversationAsRead' : IDL.Func([ConversationId], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          UserRole,
        ],
        [UserProfile],
        [],
      ),
    'removeFrequentClient' : IDL.Func([UserId], [UserProfile], []),
    'saveProduct' : IDL.Func([IDL.Text], [SavedProduct], []),
    'seedSampleData' : IDL.Func([], [IDL.Nat], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
    'trackProductView' : IDL.Func([IDL.Text], [], []),
    'unsaveProduct' : IDL.Func([IDL.Text], [], []),
    'updateConfig' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [SiteConfig],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [Order], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Bool),
          IDL.Opt(ProductCategory),
          IDL.Opt(ProductCondition),
          IDL.Opt(ProductZone),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [Product],
        [],
      ),
    'updateProductStatus' : IDL.Func([IDL.Text, ProductStatus], [Product], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
        ],
        [UserProfile],
        [],
      ),
    'updateReportStatus' : IDL.Func([IDL.Text, ReportStatus], [Report], []),
    'updateSettings' : IDL.Func([UserSettings], [UserProfile], []),
    'updateUserStatus' : IDL.Func([UserId, UserStatus], [UserProfile], []),
    'verifyUser' : IDL.Func([UserId], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };