/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    id: UserId;
    bio?: string;
    status: UserStatus;
    timezone: string;
    principal: Principal;
    verified: boolean;
    privacySearchable: boolean;
    dateOfBirth?: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    zone?: string;
    themePreference: string;
    email?: string;
    language: string;
    totalSales: bigint;
    avatarUrl?: string;
    currency: string;
    privacyShowHistory: boolean;
    frequentClients: Array<UserId>;
    phone: string;
    notificationsEmail: boolean;
    notificationsPush: boolean;
    avgRating: number;
}
export type AssetId = string;
export type Timestamp = bigint;
export interface Rating {
    id: string;
    toSellerId: UserId;
    createdAt: Timestamp;
    productId: string;
    score: bigint;
    comment: string;
    fromUserId: UserId;
}
export interface AuditLog {
    id: string;
    status: string;
    action: string;
    adminName: string;
    timestamp: Timestamp;
    details: string;
    affectedId?: string;
    adminId: UserId;
}
export interface SiteConfig {
    metaDescription: string;
    analyticsId: string;
    maintenanceMode: boolean;
    siteName: string;
    logoUrl: string;
    siteDescription: string;
    contactEmail: string;
}
export interface Report {
    id: string;
    status: ReportStatus;
    createdAt: Timestamp;
    description: string;
    adminNote?: string;
    reportType: ReportType;
    reporterId: UserId;
    entityId: string;
    reason: string;
}
export interface RevenueByDay {
    revenue: bigint;
    date: string;
}
export interface TopProduct {
    title: string;
    revenue: bigint;
    views: bigint;
    orders: bigint;
    productId: string;
}
export type ConversationId = string;
export interface ActivityEvent {
    id: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    relatedId?: string;
    eventType: string;
}
export interface ProductFilters {
    status?: ProductStatus;
    zone?: ProductZone;
    searchTerm?: string;
    category?: ProductCategory;
    priceMax?: number;
    priceMin?: number;
    condition?: ProductCondition;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export interface SellerStats {
    totalOrders: bigint;
    revenueByDay: Array<RevenueByDay>;
    conversionRate: number;
    topProducts: Array<TopProduct>;
    totalRevenue: bigint;
    avgOrderValue: bigint;
}
export interface AuditFilters {
    page: bigint;
    pageSize: bigint;
    actionType?: string;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    adminId?: UserId;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    createdAt: Timestamp;
    productId: string;
    updatedAt: Timestamp;
    buyerId: UserId;
    stripePaymentIntentId: string;
    amountMxn: bigint;
    sellerId: UserId;
}
export interface DashboardStats {
    totalProducts: bigint;
    newUsersToday: bigint;
    pendingReports: bigint;
    activeListings: bigint;
    totalReports: bigint;
    blockedProducts: bigint;
    totalUsers: bigint;
    newProductsToday: bigint;
}
export type UserId = string;
export interface OrderStats {
    totalOrders: bigint;
    ordersThisMonth: bigint;
    ordersThisWeek: bigint;
    ordersToday: bigint;
    totalRevenue: bigint;
}
export type MessageId = string;
export interface Notification {
    id: string;
    title: string;
    body: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    relatedId?: string;
}
export interface SavedProduct {
    userId: UserId;
    productId: string;
    savedAt: Timestamp;
}
export interface UserSettings {
    timezone: string;
    privacySearchable: boolean;
    themePreference: string;
    language: string;
    currency: string;
    privacyShowHistory: boolean;
    notificationsEmail: boolean;
    notificationsPush: boolean;
}
export interface Message {
    id: MessageId;
    authorId: UserId;
    text: string;
    readBySeller: boolean;
    conversationId: ConversationId;
    timestamp: Timestamp;
    readByBuyer: boolean;
}
export interface Conversation {
    id: ConversationId;
    status: ConversationStatus;
    lastMessageAt: Timestamp;
    createdAt: Timestamp;
    productId: string;
    buyerId: UserId;
    sellerId: UserId;
}
export interface Product {
    id: string;
    status: ProductStatus;
    title: string;
    isApartado: boolean;
    featured: boolean;
    views: bigint;
    createdAt: Timestamp;
    zone: ProductZone;
    description: string;
    whatsappContact?: string;
    category: ProductCategory;
    sellerId: UserId;
    colony: string;
    price: number;
    photos: Array<AssetId>;
    negotiable: boolean;
    condition: ProductCondition;
}
export type OrderId = string;
export enum ConversationStatus {
    active = "active",
    archived = "archived"
}
export enum NotificationType {
    newProduct = "newProduct",
    newMessage = "newMessage",
    productUpdate = "productUpdate"
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded",
    failed = "failed"
}
export enum ProductCategory {
    mueble = "mueble",
    auto = "auto",
    otro = "otro",
    ropa = "ropa",
    electronico = "electronico"
}
export enum ProductCondition {
    nuevo = "nuevo",
    usado = "usado"
}
export enum ProductStatus {
    active = "active",
    blocked = "blocked",
    hidden = "hidden",
    paused = "paused"
}
export enum ProductZone {
    centro = "centro",
    playas = "playas",
    otay = "otay",
    corredor2000 = "corredor2000"
}
export enum ReportStatus {
    new_ = "new",
    resolved = "resolved",
    inReview = "inReview"
}
export enum ReportType {
    chat = "chat",
    user = "user",
    product = "product"
}
export enum UserRole {
    admin = "admin",
    vendedor = "vendedor",
    comprador = "comprador"
}
export enum UserStatus {
    active = "active",
    banned = "banned",
    suspended = "suspended"
}
export interface backendInterface {
    addAdminNote(reportId: string, note: string): Promise<Report>;
    addFrequentClient(sellerId: UserId): Promise<UserProfile>;
    addRating(toSellerId: UserId, productId: string, score: bigint, comment: string): Promise<Rating>;
    chatWithAviBot(message: string, conversationHistory: Array<ChatMessage>): Promise<string>;
    createCheckoutSession(productId: string, successUrl: string, cancelUrl: string): Promise<{
        checkoutUrl: string;
    }>;
    createConversation(sellerId: UserId, productId: string): Promise<Conversation>;
    createOrder(productId: string, sellerId: UserId, amountMxn: bigint, stripePaymentIntentId: string): Promise<Order>;
    createProduct(title: string, description: string, price: number, negotiable: boolean, category: ProductCategory, condition: ProductCondition, zone: ProductZone, colony: string, photos: Array<string>, whatsappContact: string | null, isApartado: boolean): Promise<Product>;
    createReport(reportType: ReportType, entityId: string, reason: string, description: string): Promise<Report>;
    deleteProduct(productId: string): Promise<void>;
    deleteUser(targetId: UserId): Promise<void>;
    featureProduct(productId: string, featured: boolean): Promise<Product>;
    getActivityByUser(userId: UserId): Promise<Array<ActivityEvent>>;
    getConfig(): Promise<SiteConfig>;
    getConversationMessages(conversationId: ConversationId): Promise<Array<Message>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMyActivity(): Promise<Array<ActivityEvent>>;
    getMyConversations(): Promise<Array<Conversation>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyRatings(): Promise<Array<Rating>>;
    getMySavedProducts(): Promise<Array<SavedProduct>>;
    getMySellerOrders(): Promise<Array<Order>>;
    getProduct(productId: string): Promise<Product | null>;
    getProductPhotoIds(productId: string): Promise<Array<string>>;
    getProductViewCount(productId: string): Promise<bigint>;
    getProductsByVendor(sellerId: UserId): Promise<Array<Product>>;
    getRatingsBySeller(sellerId: UserId): Promise<Array<Rating>>;
    getSellerOrderStats(): Promise<OrderStats>;
    getSellerStats(): Promise<SellerStats>;
    getUnreadCount(): Promise<bigint>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserById(userId: UserId): Promise<UserProfile | null>;
    incrementProductViews(productId: string): Promise<void>;
    isMaintenanceMode(): Promise<boolean>;
    listAuditLogs(filters: AuditFilters): Promise<Array<AuditLog>>;
    listMyActivity(): Promise<Array<ActivityEvent>>;
    listProducts(filters: ProductFilters): Promise<Array<Product>>;
    listReports(): Promise<Array<Report>>;
    listUsers(): Promise<Array<UserProfile>>;
    markAllNotificationsRead(): Promise<void>;
    markConversationAsRead(conversationId: ConversationId): Promise<void>;
    markNotificationRead(notifId: string): Promise<void>;
    registerUser(name: string, phone: string, email: string | null, avatarUrl: string | null, bio: string | null, zone: string | null, role: UserRole): Promise<UserProfile>;
    removeFrequentClient(sellerId: UserId): Promise<UserProfile>;
    saveProduct(productId: string): Promise<SavedProduct>;
    seedSampleData(): Promise<bigint>;
    sendMessage(conversationId: ConversationId, text: string): Promise<Message>;
    trackProductView(productId: string): Promise<void>;
    unsaveProduct(productId: string): Promise<void>;
    updateConfig(siteName: string | null, siteDescription: string | null, logoUrl: string | null, contactEmail: string | null, maintenanceMode: boolean | null, analyticsId: string | null, metaDescription: string | null): Promise<SiteConfig>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<Order>;
    updateProduct(productId: string, title: string | null, description: string | null, price: number | null, negotiable: boolean | null, category: ProductCategory | null, condition: ProductCondition | null, zone: ProductZone | null, colony: string | null, photos: Array<string> | null, whatsappContact: string | null, isApartado: boolean | null): Promise<Product>;
    updateProductStatus(productId: string, status: ProductStatus): Promise<Product>;
    updateProfile(name: string | null, email: string | null, avatarUrl: string | null, bio: string | null, zone: string | null, dateOfBirth: string | null, privacySearchable: boolean | null, privacyShowHistory: boolean | null, themePreference: string | null, language: string | null, timezone: string | null, currency: string | null, notificationsEmail: boolean | null, notificationsPush: boolean | null): Promise<UserProfile>;
    updateReportStatus(reportId: string, status: ReportStatus): Promise<Report>;
    updateSettings(settings: UserSettings): Promise<UserProfile>;
    updateUserStatus(targetId: UserId, status: UserStatus): Promise<UserProfile>;
    verifyUser(targetId: UserId): Promise<UserProfile>;
}
import type { ActivityEvent as _ActivityEvent, AssetId as _AssetId, AuditFilters as _AuditFilters, AuditLog as _AuditLog, Conversation as _Conversation, ConversationId as _ConversationId, ConversationStatus as _ConversationStatus, Notification as _Notification, NotificationType as _NotificationType, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Product as _Product, ProductCategory as _ProductCategory, ProductCondition as _ProductCondition, ProductFilters as _ProductFilters, ProductStatus as _ProductStatus, ProductZone as _ProductZone, Report as _Report, ReportStatus as _ReportStatus, ReportType as _ReportType, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserStatus as _UserStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdminNote(arg0: string, arg1: string): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminNote(arg0, arg1);
                return from_candid_Report_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminNote(arg0, arg1);
            return from_candid_Report_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFrequentClient(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.addFrequentClient(arg0);
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFrequentClient(arg0);
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRating(arg0: UserId, arg1: string, arg2: bigint, arg3: string): Promise<Rating> {
        if (this.processError) {
            try {
                const result = await this.actor.addRating(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRating(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async chatWithAviBot(arg0: string, arg1: Array<ChatMessage>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.chatWithAviBot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatWithAviBot(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: string, arg1: string, arg2: string): Promise<{
        checkoutUrl: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createConversation(arg0: UserId, arg1: string): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0, arg1);
                return from_candid_Conversation_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0, arg1);
            return from_candid_Conversation_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: string, arg1: UserId, arg2: bigint, arg3: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
                return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
            return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: number, arg3: boolean, arg4: ProductCategory, arg5: ProductCondition, arg6: ProductZone, arg7: string, arg8: Array<string>, arg9: string | null, arg10: boolean): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, to_candid_ProductCategory_n22(this._uploadFile, this._downloadFile, arg4), to_candid_ProductCondition_n24(this._uploadFile, this._downloadFile, arg5), to_candid_ProductZone_n26(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg9), arg10);
                return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, to_candid_ProductCategory_n22(this._uploadFile, this._downloadFile, arg4), to_candid_ProductCondition_n24(this._uploadFile, this._downloadFile, arg5), to_candid_ProductZone_n26(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg9), arg10);
            return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReport(arg0: ReportType, arg1: string, arg2: string, arg3: string): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(to_candid_ReportType_n39(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_Report_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(to_candid_ReportType_n39(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_Report_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async featureProduct(arg0: string, arg1: boolean): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.featureProduct(arg0, arg1);
                return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.featureProduct(arg0, arg1);
            return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityByUser(arg0: UserId): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityByUser(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityByUser(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfig(): Promise<SiteConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfig();
            return result;
        }
    }
    async getConversationMessages(arg0: ConversationId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversationMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversationMessages(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyActivity(): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActivity();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActivity();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConversations();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConversations();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRatings(): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRatings();
            return result;
        }
    }
    async getMySavedProducts(): Promise<Array<SavedProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySavedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySavedProducts();
            return result;
        }
    }
    async getMySellerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySellerOrders();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySellerOrders();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductPhotoIds(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductPhotoIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductPhotoIds(arg0);
            return result;
        }
    }
    async getProductViewCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductViewCount(arg0);
            return result;
        }
    }
    async getProductsByVendor(arg0: UserId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByVendor(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByVendor(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingsBySeller(arg0: UserId): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsBySeller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsBySeller(arg0);
            return result;
        }
    }
    async getSellerOrderStats(): Promise<OrderStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerOrderStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerOrderStats();
            return result;
        }
    }
    async getSellerStats(): Promise<SellerStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerStats();
            return result;
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserById(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementProductViews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementProductViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementProductViews(arg0);
            return result;
        }
    }
    async isMaintenanceMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMaintenanceMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMaintenanceMode();
            return result;
        }
    }
    async listAuditLogs(arg0: AuditFilters): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAuditLogs(to_candid_AuditFilters_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAuditLogs(to_candid_AuditFilters_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyActivity(): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyActivity();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyActivity();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductFilters): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilters_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilters_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markConversationAsRead(arg0: ConversationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationAsRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: UserRole): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg5), to_candid_UserRole_n65(this._uploadFile, this._downloadFile, arg6));
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg5), to_candid_UserRole_n65(this._uploadFile, this._downloadFile, arg6));
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFrequentClient(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFrequentClient(arg0);
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFrequentClient(arg0);
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProduct(arg0: string): Promise<SavedProduct> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProduct(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async sendMessage(arg0: ConversationId, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async trackProductView(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackProductView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackProductView(arg0);
            return result;
        }
    }
    async unsaveProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveProduct(arg0);
            return result;
        }
    }
    async updateConfig(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: boolean | null, arg5: string | null, arg6: string | null): Promise<SiteConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfig(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfig(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: string, arg1: string | null, arg2: string | null, arg3: number | null, arg4: boolean | null, arg5: ProductCategory | null, arg6: ProductCondition | null, arg7: ProductZone | null, arg8: string | null, arg9: Array<string> | null, arg10: string | null, arg11: boolean | null): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n70(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n72(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n73(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n74(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg11));
                return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n70(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n72(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n73(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n74(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg11));
            return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProductStatus(arg0: string, arg1: ProductStatus): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductStatus(arg0, to_candid_ProductStatus_n61(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductStatus(arg0, to_candid_ProductStatus_n61(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Product_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: boolean | null, arg7: boolean | null, arg8: string | null, arg9: string | null, arg10: string | null, arg11: string | null, arg12: boolean | null, arg13: boolean | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg13));
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg13));
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReportStatus(arg0: string, arg1: ReportStatus): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n75(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Report_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n75(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Report_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: UserSettings): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserStatus(arg0: UserId, arg1: UserStatus): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, to_candid_UserStatus_n77(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, to_candid_UserStatus_n77(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyUser(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUser(arg0);
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUser(arg0);
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityEvent_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEvent): ActivityEvent {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLog_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationStatus): ConversationStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCondition_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCondition): ProductCondition {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ProductStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductStatus): ProductStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ProductZone_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductZone): ProductZone {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ReportType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportType): ReportType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    status: _ConversationStatus;
    lastMessageAt: _Timestamp;
    createdAt: _Timestamp;
    productId: string;
    buyerId: _UserId;
    sellerId: _UserId;
}): {
    id: ConversationId;
    status: ConversationStatus;
    lastMessageAt: Timestamp;
    createdAt: Timestamp;
    productId: string;
    buyerId: UserId;
    sellerId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ConversationStatus_n16(_uploadFile, _downloadFile, value.status),
        lastMessageAt: value.lastMessageAt,
        createdAt: value.createdAt,
        productId: value.productId,
        buyerId: value.buyerId,
        sellerId: value.sellerId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    createdAt: _Timestamp;
    productId: string;
    updatedAt: _Timestamp;
    buyerId: _UserId;
    stripePaymentIntentId: string;
    amountMxn: bigint;
    sellerId: _UserId;
}): {
    id: OrderId;
    status: OrderStatus;
    createdAt: Timestamp;
    productId: string;
    updatedAt: Timestamp;
    buyerId: UserId;
    stripePaymentIntentId: string;
    amountMxn: bigint;
    sellerId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        productId: value.productId,
        updatedAt: value.updatedAt,
        buyerId: value.buyerId,
        stripePaymentIntentId: value.stripePaymentIntentId,
        amountMxn: value.amountMxn,
        sellerId: value.sellerId
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ReportStatus;
    createdAt: _Timestamp;
    description: string;
    adminNote: [] | [string];
    reportType: _ReportType;
    reporterId: _UserId;
    entityId: string;
    reason: string;
}): {
    id: string;
    status: ReportStatus;
    createdAt: Timestamp;
    description: string;
    adminNote?: string;
    reportType: ReportType;
    reporterId: UserId;
    entityId: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n3(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        description: value.description,
        adminNote: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.adminNote)),
        reportType: from_candid_ReportType_n6(_uploadFile, _downloadFile, value.reportType),
        reporterId: value.reporterId,
        entityId: value.entityId,
        reason: value.reason
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ProductStatus;
    title: string;
    isApartado: boolean;
    featured: boolean;
    views: bigint;
    createdAt: _Timestamp;
    zone: _ProductZone;
    description: string;
    whatsappContact: [] | [string];
    category: _ProductCategory;
    sellerId: _UserId;
    colony: string;
    price: number;
    photos: Array<_AssetId>;
    negotiable: boolean;
    condition: _ProductCondition;
}): {
    id: string;
    status: ProductStatus;
    title: string;
    isApartado: boolean;
    featured: boolean;
    views: bigint;
    createdAt: Timestamp;
    zone: ProductZone;
    description: string;
    whatsappContact?: string;
    category: ProductCategory;
    sellerId: UserId;
    colony: string;
    price: number;
    photos: Array<AssetId>;
    negotiable: boolean;
    condition: ProductCondition;
} {
    return {
        id: value.id,
        status: from_candid_ProductStatus_n31(_uploadFile, _downloadFile, value.status),
        title: value.title,
        isApartado: value.isApartado,
        featured: value.featured,
        views: value.views,
        createdAt: value.createdAt,
        zone: from_candid_ProductZone_n33(_uploadFile, _downloadFile, value.zone),
        description: value.description,
        whatsappContact: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.whatsappContact)),
        category: from_candid_ProductCategory_n35(_uploadFile, _downloadFile, value.category),
        sellerId: value.sellerId,
        colony: value.colony,
        price: value.price,
        photos: value.photos,
        negotiable: value.negotiable,
        condition: from_candid_ProductCondition_n37(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userId: _UserId;
    description: string;
    timestamp: _Timestamp;
    relatedId: [] | [string];
    eventType: string;
}): {
    id: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    relatedId?: string;
    eventType: string;
} {
    return {
        id: value.id,
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp,
        relatedId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.relatedId)),
        eventType: value.eventType
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
    relatedId: [] | [string];
}): {
    id: string;
    title: string;
    body: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    relatedId?: string;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n48(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        relatedId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.relatedId))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    action: string;
    adminName: string;
    timestamp: _Timestamp;
    details: string;
    affectedId: [] | [string];
    adminId: _UserId;
}): {
    id: string;
    status: string;
    action: string;
    adminName: string;
    timestamp: Timestamp;
    details: string;
    affectedId?: string;
    adminId: UserId;
} {
    return {
        id: value.id,
        status: value.status,
        action: value.action,
        adminName: value.adminName,
        timestamp: value.timestamp,
        details: value.details,
        affectedId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.affectedId)),
        adminId: value.adminId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    status: _UserStatus;
    timezone: string;
    principal: Principal;
    verified: boolean;
    privacySearchable: boolean;
    dateOfBirth: [] | [string];
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    zone: [] | [string];
    themePreference: string;
    email: [] | [string];
    language: string;
    totalSales: bigint;
    avatarUrl: [] | [string];
    currency: string;
    privacyShowHistory: boolean;
    frequentClients: Array<_UserId>;
    phone: string;
    notificationsEmail: boolean;
    notificationsPush: boolean;
    avgRating: number;
}): {
    id: UserId;
    bio?: string;
    status: UserStatus;
    timezone: string;
    principal: Principal;
    verified: boolean;
    privacySearchable: boolean;
    dateOfBirth?: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    zone?: string;
    themePreference: string;
    email?: string;
    language: string;
    totalSales: bigint;
    avatarUrl?: string;
    currency: string;
    privacyShowHistory: boolean;
    frequentClients: Array<UserId>;
    phone: string;
    notificationsEmail: boolean;
    notificationsPush: boolean;
    avgRating: number;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bio)),
        status: from_candid_UserStatus_n10(_uploadFile, _downloadFile, value.status),
        timezone: value.timezone,
        principal: value.principal,
        verified: value.verified,
        privacySearchable: value.privacySearchable,
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.dateOfBirth)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        zone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.zone)),
        themePreference: value.themePreference,
        email: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.email)),
        language: value.language,
        totalSales: value.totalSales,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.avatarUrl)),
        currency: value.currency,
        privacyShowHistory: value.privacyShowHistory,
        frequentClients: value.frequentClients,
        phone: value.phone,
        notificationsEmail: value.notificationsEmail,
        notificationsPush: value.notificationsPush,
        avgRating: value.avgRating
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    banned: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "banned" in value ? UserStatus.banned : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    vendedor: null;
} | {
    comprador: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "vendedor" in value ? UserRole.vendedor : "comprador" in value ? UserRole.comprador : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    archived: null;
}): ConversationStatus {
    return "active" in value ? ConversationStatus.active : "archived" in value ? ConversationStatus.archived : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "refunded" in value ? OrderStatus.refunded : "failed" in value ? OrderStatus.failed : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    blocked: null;
} | {
    hidden: null;
} | {
    paused: null;
}): ProductStatus {
    return "active" in value ? ProductStatus.active : "blocked" in value ? ProductStatus.blocked : "hidden" in value ? ProductStatus.hidden : "paused" in value ? ProductStatus.paused : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    centro: null;
} | {
    playas: null;
} | {
    otay: null;
} | {
    corredor2000: null;
}): ProductZone {
    return "centro" in value ? ProductZone.centro : "playas" in value ? ProductZone.playas : "otay" in value ? ProductZone.otay : "corredor2000" in value ? ProductZone.corredor2000 : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mueble: null;
} | {
    auto: null;
} | {
    otro: null;
} | {
    ropa: null;
} | {
    electronico: null;
}): ProductCategory {
    return "mueble" in value ? ProductCategory.mueble : "auto" in value ? ProductCategory.auto : "otro" in value ? ProductCategory.otro : "ropa" in value ? ProductCategory.ropa : "electronico" in value ? ProductCategory.electronico : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nuevo: null;
} | {
    usado: null;
}): ProductCondition {
    return "nuevo" in value ? ProductCondition.nuevo : "usado" in value ? ProductCondition.usado : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    resolved: null;
} | {
    inReview: null;
}): ReportStatus {
    return "new" in value ? ReportStatus.new : "resolved" in value ? ReportStatus.resolved : "inReview" in value ? ReportStatus.inReview : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newProduct: null;
} | {
    newMessage: null;
} | {
    productUpdate: null;
}): NotificationType {
    return "newProduct" in value ? NotificationType.newProduct : "newMessage" in value ? NotificationType.newMessage : "productUpdate" in value ? NotificationType.productUpdate : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chat: null;
} | {
    user: null;
} | {
    product: null;
}): ReportType {
    return "chat" in value ? ReportType.chat : "user" in value ? ReportType.user : "product" in value ? ReportType.product : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEvent>): Array<ActivityEvent> {
    return value.map((x)=>from_candid_ActivityEvent_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AuditFilters_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditFilters): _AuditFilters {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCondition_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition): _ProductCondition {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilters_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilters): _ProductFilters {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_ProductStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductStatus): _ProductStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_ProductZone_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductZone): _ProductZone {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_ReportType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): _ReportType {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory | null): [] | [_ProductCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ProductCategory_n22(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition | null): [] | [_ProductCondition] {
    return value === null ? candid_none() : candid_some(to_candid_ProductCondition_n24(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductZone | null): [] | [_ProductZone] {
    return value === null ? candid_none() : candid_some(to_candid_ProductZone_n26(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    page: bigint;
    pageSize: bigint;
    actionType?: string;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    adminId?: UserId;
}): {
    page: bigint;
    pageSize: bigint;
    actionType: [] | [string];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    adminId: [] | [_UserId];
} {
    return {
        page: value.page,
        pageSize: value.pageSize,
        actionType: value.actionType ? candid_some(value.actionType) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        adminId: value.adminId ? candid_some(value.adminId) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ProductStatus;
    zone?: ProductZone;
    searchTerm?: string;
    category?: ProductCategory;
    priceMax?: number;
    priceMin?: number;
    condition?: ProductCondition;
}): {
    status: [] | [_ProductStatus];
    zone: [] | [_ProductZone];
    searchTerm: [] | [string];
    category: [] | [_ProductCategory];
    priceMax: [] | [number];
    priceMin: [] | [number];
    condition: [] | [_ProductCondition];
} {
    return {
        status: value.status ? candid_some(to_candid_ProductStatus_n61(_uploadFile, _downloadFile, value.status)) : candid_none(),
        zone: value.zone ? candid_some(to_candid_ProductZone_n26(_uploadFile, _downloadFile, value.zone)) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        category: value.category ? candid_some(to_candid_ProductCategory_n22(_uploadFile, _downloadFile, value.category)) : candid_none(),
        priceMax: value.priceMax ? candid_some(value.priceMax) : candid_none(),
        priceMin: value.priceMin ? candid_some(value.priceMin) : candid_none(),
        condition: value.condition ? candid_some(to_candid_ProductCondition_n24(_uploadFile, _downloadFile, value.condition)) : candid_none()
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    mueble: null;
} | {
    auto: null;
} | {
    otro: null;
} | {
    ropa: null;
} | {
    electronico: null;
} {
    return value == ProductCategory.mueble ? {
        mueble: null
    } : value == ProductCategory.auto ? {
        auto: null
    } : value == ProductCategory.otro ? {
        otro: null
    } : value == ProductCategory.ropa ? {
        ropa: null
    } : value == ProductCategory.electronico ? {
        electronico: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCondition): {
    nuevo: null;
} | {
    usado: null;
} {
    return value == ProductCondition.nuevo ? {
        nuevo: null
    } : value == ProductCondition.usado ? {
        usado: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductZone): {
    centro: null;
} | {
    playas: null;
} | {
    otay: null;
} | {
    corredor2000: null;
} {
    return value == ProductZone.centro ? {
        centro: null
    } : value == ProductZone.playas ? {
        playas: null
    } : value == ProductZone.otay ? {
        otay: null
    } : value == ProductZone.corredor2000 ? {
        corredor2000: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): {
    chat: null;
} | {
    user: null;
} | {
    product: null;
} {
    return value == ReportType.chat ? {
        chat: null
    } : value == ReportType.user ? {
        user: null
    } : value == ReportType.product ? {
        product: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductStatus): {
    active: null;
} | {
    blocked: null;
} | {
    hidden: null;
} | {
    paused: null;
} {
    return value == ProductStatus.active ? {
        active: null
    } : value == ProductStatus.blocked ? {
        blocked: null
    } : value == ProductStatus.hidden ? {
        hidden: null
    } : value == ProductStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    vendedor: null;
} | {
    comprador: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.vendedor ? {
        vendedor: null
    } : value == UserRole.comprador ? {
        comprador: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.refunded ? {
        refunded: null
    } : value == OrderStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    new: null;
} | {
    resolved: null;
} | {
    inReview: null;
} {
    return value == ReportStatus.new ? {
        new_: null
    } : value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.inReview ? {
        inReview: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    banned: null;
} | {
    suspended: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.banned ? {
        banned: null
    } : value == UserStatus.suspended ? {
        suspended: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
